### ISSUE TITLE
README.MD missing BreakpointEvent moved to core

### ISSUE THREAD

**Issue by b2ag** [Jay184/PyPS4debug#3]
Hi,

I had some trouble following the `README.MD` when it came to using `BreakpointEvent` as it seems to have moved from `ps4debug.BreakpointEvent` to `ps4debug.core.BreakpointEvent`. As I'm new to it and only reached that point so far while not exactly copying the code from the `README.MD` I opted to not pull request an untested change. Could do it later though if you want me to.

Best,
b2ag

**Comment by b2ag** [comment]
Also looks like `set_breakpoint` is a coroutine and has to be awaited.
```python
async with ps4.debugger(pid, resume=True) as debugger:
    debugger.set_breakpoint(0, True, address, on_hit=callback)
```

**Comment by Jay184** [comment]
Hi, excuse me for the late reply. You are correct, I must have missed those two examples when refactoring to an async framework. I'll adjust the `README.md` soon.

**Comment by Jay184** [comment]
With 3234358bb58050fe6d1b17616c22298363eceb18 the `README.md` should be adjusted to the actual codebase now. Thanks for using the library!
