### ISSUE TITLE
Make Timeout a Parameter (Feature Request)

### ISSUE THREAD

**Issue by b2ag** [Jay184/PyPS4debug#8]
Hi,

I poked around with your nice library, but tend to crash the console more often than I would like. Reconnecting makes me stumble upon this hard coded timeout, I would like to set a lot lower so payload sending kicks in quicker. Can I have that e.g. by means of an extra parameter to `find_ps4` ? Would be awesome :racehorse: 

https://github.com/Jay184/PyPS4debug/blob/3234358bb58050fe6d1b17616c22298363eceb18/src/ps4debug/__init__.py#L451

Sending the payload is coded conditionally for the case that `find_ps4` fails in my humble debugger (aka console crasher) script.

Best,
b2ag

**Comment by Jay184** [comment]
Hi. Thanks for your compliment, I'm glad the library is useful to you.

You're right, making the timeout a parameter would be a much better call here, especially with the start-up times of the console sometimes.

I'll get that in as soon as possible.
